# Generated by Django 5.0.7 on 2024-07-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text_content',
            field=models.CharField(max_length=500),
        ),
    ]
